### ISSUE TITLE
TODO: Menu principal

### ISSUE THREAD

**Issue by DragonOfWar** [ColmeiaUDESC/gamejaaj6#15]
# Tela Principal

## Botoes

- [ ] Iniciar jogo -> Vai pra tela de escolha de save
- [ ] Opções (PRIORIDADE MINIMA) -> Vai pra tela de opções
- [ ] Sair -> Sai do jogo

## Arte

- [ ] Titulo
- [ ] Fundo
- [ ] Botao

# Tela Saves

Esta tela vai conter três opções, cada um representando um save. As saves possuem progresso independentes entre si

## Botoes

- [ ] Save -> vai para tela principal do save
- [ ] Voltar -> volta pra tela principal

## Arte

Reutilizar assets da tela principal (fundo, etc)
- [ ] Arte de cada save (da pra fazer cada save um botao normal, dai economiza tempo)

# Tela principal do save

Esta tela é onde o jogador pode iniciar o jogo.
Se der tempo, utilizar um espaço dessa tela pra mostrar as "conquistas", ou seja, quais finais o jogador conseguiu atingir com cada personagem.
Talvez também dizer qual é o personagem atual e suas estatísticas.

## Botoes

- [ ] Iniciar jogo -> inicia o jogo
- [ ] Voltar -> volta pra tela dos saves

## Arte

Reutilizar assets da tela principal
- [ ] Artes da seção de conquistas
